name = "suika_programing"
description = "Suika game clone with programing languages"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]
licenses = "MIT"
website = "https://github.com/Fabien-Chouteau/suika-programing"
tags = ["game", "suika", "raylib", "chipmunk", "physics", "2d"]

executables = ["suika_programing"]

[[depends-on]]
raylib = "^1.0.0"
resources = "~0.1.0"
box2d = "*"
box2d_raylib_debug = "*"

[[pins]]
box2d = { url='git@github.com:Fabien-Chouteau/box2d-ada.git' }
box2d_raylib_debug = { url='git@github.com:Fabien-Chouteau/box2d-ada.git', subdir="box2d_raylib_debug/" }

